version: "3.10"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  app:
    build: .
    command: ["python3", "app.py"]
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    env_file: .env

  main:
    build: .
    depends_on:
      - redis
    env_file: .env
    command: [ "python3", "job.py" ]